//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.JPBSDSJDFProyectoIPS.IoTModelDiagram")]

namespace UPM_IPS.JPBSDSJDFProyectoIPS
{
	/// <summary>
	/// DomainClass IoTModelDiagram
	/// Description for UPM_IPS.JPBSDSJDFProyectoIPS.IoTModelDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JPBSDSJDFProyectoIPS.IoTModelDiagram.DisplayName", typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSDomainModel), "UPM_IPS.JPBSDSJDFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JPBSDSJDFProyectoIPS.IoTModelDiagram.Description", typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSDomainModel), "UPM_IPS.JPBSDSJDFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("0471c6bf-22f1-4200-9aea-08ce487208e8")]
	public partial class IoTModelDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.Temperatue)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.TemperatureImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.TemperatureImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.Infrared)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.InfraredImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.InfraredImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.LightSensor)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.LightSensorImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.LightSensorImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.LedActuator)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.LedActuarionImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.LedActuarionImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.LCDActuator)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.LCDActuatorImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.LCDActuatorImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.BuzzerActuator)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.BuzzerActuatorImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.BuzzerActuatorImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.DCMotorActuator)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.DCMotorActuatorImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.DCMotorActuatorImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.SensorShape newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.SensorShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ControllerGeom newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ControllerGeom(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesSensors)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIoSens newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIoSens(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.If)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IfImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IfImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.Delay)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.DelayImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.DelayImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.IO)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IOImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IOImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.IfReferencesIO)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIfIo newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIfIo(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesContoller)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecArduContro newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecArduContro(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesSensors)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ArdSens newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ArdSens(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.IfReferencesDelay)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIfDelay newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIfDelay(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesActuators)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIoActua newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIoActua(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.Arduino)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoImg newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoImg(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesActuators)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.Connec_Ard_Actu newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.Connec_Ard_Actu(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesDelay)
			{
				global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIODelay newShape = new global::UPM_IPS.JPBSDSJDFProyectoIPS.ConnecIODelay(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.Connec_Ard_SensorConnectAction connec_Ard_SensorConnectAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnec_Ard_ActConnectAction iconConnec_Ard_ActConnectAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecArdControConnectAction iconConnecArdControConnectAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfIoConnectAction iconConnecIfIoConnectAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfDelayConnectAction iconConnecIfDelayConnectAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoActuaConnectAction iconConnecIoActuaConnectAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoSensConnectAction iconConnecIoSensConnectAction;
		private global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoDelayConnectAction iconConnecIoDelayConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.Connec_Ard_SensorFilterString))
				{
					if (this.connec_Ard_SensorConnectAction == null)
					{
						this.connec_Ard_SensorConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.Connec_Ard_SensorConnectAction(this);
						this.connec_Ard_SensorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.connec_Ard_SensorConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.IconConnec_Ard_ActFilterString))
				{
					if (this.iconConnec_Ard_ActConnectAction == null)
					{
						this.iconConnec_Ard_ActConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnec_Ard_ActConnectAction(this);
						this.iconConnec_Ard_ActConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.iconConnec_Ard_ActConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.IconConnecArdControFilterString))
				{
					if (this.iconConnecArdControConnectAction == null)
					{
						this.iconConnecArdControConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecArdControConnectAction(this);
						this.iconConnecArdControConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.iconConnecArdControConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.IconConnecIfIoFilterString))
				{
					if (this.iconConnecIfIoConnectAction == null)
					{
						this.iconConnecIfIoConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfIoConnectAction(this);
						this.iconConnecIfIoConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.iconConnecIfIoConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.IconConnecIfDelayFilterString))
				{
					if (this.iconConnecIfDelayConnectAction == null)
					{
						this.iconConnecIfDelayConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfDelayConnectAction(this);
						this.iconConnecIfDelayConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.iconConnecIfDelayConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.IconConnecIoActuaFilterString))
				{
					if (this.iconConnecIoActuaConnectAction == null)
					{
						this.iconConnecIoActuaConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoActuaConnectAction(this);
						this.iconConnecIoActuaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.iconConnecIoActuaConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.IconConnecIoSensFilterString))
				{
					if (this.iconConnecIoSensConnectAction == null)
					{
						this.iconConnecIoSensConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoSensConnectAction(this);
						this.iconConnecIoSensConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.iconConnecIoSensConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxHelper.IconConnecIoDelayFilterString))
				{
					if (this.iconConnecIoDelayConnectAction == null)
					{
						this.iconConnecIoDelayConnectAction = new global::UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoDelayConnectAction(this);
						this.iconConnecIoDelayConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.iconConnecIoDelayConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.connec_Ard_SensorConnectAction != null)
					{
						this.connec_Ard_SensorConnectAction.Dispose();
						this.connec_Ard_SensorConnectAction = null;
					}
					if(this.iconConnec_Ard_ActConnectAction != null)
					{
						this.iconConnec_Ard_ActConnectAction.Dispose();
						this.iconConnec_Ard_ActConnectAction = null;
					}
					if(this.iconConnecArdControConnectAction != null)
					{
						this.iconConnecArdControConnectAction.Dispose();
						this.iconConnecArdControConnectAction = null;
					}
					if(this.iconConnecIfIoConnectAction != null)
					{
						this.iconConnecIfIoConnectAction.Dispose();
						this.iconConnecIfIoConnectAction = null;
					}
					if(this.iconConnecIfDelayConnectAction != null)
					{
						this.iconConnecIfDelayConnectAction.Dispose();
						this.iconConnecIfDelayConnectAction = null;
					}
					if(this.iconConnecIoActuaConnectAction != null)
					{
						this.iconConnecIoActuaConnectAction.Dispose();
						this.iconConnecIoActuaConnectAction = null;
					}
					if(this.iconConnecIoSensConnectAction != null)
					{
						this.iconConnecIoSensConnectAction.Dispose();
						this.iconConnecIoSensConnectAction = null;
					}
					if(this.iconConnecIoDelayConnectAction != null)
					{
						this.iconConnecIoDelayConnectAction.Dispose();
						this.iconConnecIoDelayConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// IoTModelDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0471c6bf, 0x22f1, 0x4200, 0x9a, 0xea, 0x08, 0xce, 0x48, 0x72, 0x08, 0xe8);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IoTModelDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IoTModelDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.JPBSDSJDFProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.Temperatue), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.Infrared), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.LightSensor), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.LedActuator), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.LCDActuator), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.BuzzerActuator), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.DCMotorActuator), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.Arduino), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesActuators), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IfReferencesDelay), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IfReferencesIO), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesContoller), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesActuators), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IO), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.Delay), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.If), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesSensors), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesSensors), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesDelay), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.Temperatue)
				{
					parentElement = GetParentForTemperatue((global::UPM_IPS.JPBSDSJDFProyectoIPS.Temperatue)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.Infrared)
				{
					parentElement = GetParentForInfrared((global::UPM_IPS.JPBSDSJDFProyectoIPS.Infrared)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.LightSensor)
				{
					parentElement = GetParentForLightSensor((global::UPM_IPS.JPBSDSJDFProyectoIPS.LightSensor)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.LedActuator)
				{
					parentElement = GetParentForLedActuator((global::UPM_IPS.JPBSDSJDFProyectoIPS.LedActuator)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.LCDActuator)
				{
					parentElement = GetParentForLCDActuator((global::UPM_IPS.JPBSDSJDFProyectoIPS.LCDActuator)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.BuzzerActuator)
				{
					parentElement = GetParentForBuzzerActuator((global::UPM_IPS.JPBSDSJDFProyectoIPS.BuzzerActuator)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.DCMotorActuator)
				{
					parentElement = GetParentForDCMotorActuator((global::UPM_IPS.JPBSDSJDFProyectoIPS.DCMotorActuator)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.Arduino)
				{
					parentElement = GetParentForArduino((global::UPM_IPS.JPBSDSJDFProyectoIPS.Arduino)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.IO)
				{
					parentElement = GetParentForIO((global::UPM_IPS.JPBSDSJDFProyectoIPS.IO)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.Delay)
				{
					parentElement = GetParentForDelay((global::UPM_IPS.JPBSDSJDFProyectoIPS.Delay)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.If)
				{
					parentElement = GetParentForIf((global::UPM_IPS.JPBSDSJDFProyectoIPS.If)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller)
				{
					parentElement = GetParentForContoller((global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller)childElement);
				} else
				if(childElement is global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors)
				{
					parentElement = GetParentForSensors((global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForArduino( global::UPM_IPS.JPBSDSJDFProyectoIPS.Arduino root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForSensors( global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForTemperatue( global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForInfrared( global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForContoller( global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForLightSensor( global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForLedActuator( global::UPM_IPS.JPBSDSJDFProyectoIPS.Actuators root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForLCDActuator( global::UPM_IPS.JPBSDSJDFProyectoIPS.Actuators root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForBuzzerActuator( global::UPM_IPS.JPBSDSJDFProyectoIPS.Actuators root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForDCMotorActuator( global::UPM_IPS.JPBSDSJDFProyectoIPS.Actuators root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForIO( global::UPM_IPS.JPBSDSJDFProyectoIPS.IO root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller root2 = root.Contoller;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root2.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForIf( global::UPM_IPS.JPBSDSJDFProyectoIPS.If root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller root2 = root.Contoller;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root2.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel GetParentForDelay( global::UPM_IPS.JPBSDSJDFProyectoIPS.Delay root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller root2 = root.Contoller;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModel result = root2.IoTModel;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesSensors), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesActuators), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.ArduinoReferencesContoller), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IfReferencesIO), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IfReferencesDelay), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesActuators), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesSensors), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.IOReferencesDelay), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModelDiagram diagram = linkShape.Diagram as global::UPM_IPS.JPBSDSJDFProyectoIPS.IoTModelDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
