//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace UPM_IPS.JPBSDSJDFProyectoIPS
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class JPBSDSJDFProyectoIPSToolboxHelper : JPBSDSJDFProyectoIPSToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new JPBSDSJDFProyectoIPSToolboxHelper.
		/// </summary>
		public JPBSDSJDFProyectoIPSToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class JPBSDSJDFProyectoIPSToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify JPBSDSJDFProyectoIPS toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "JPBSDSJDFProyectoIPS.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Connec_Ard_Sensor connector tool.
		/// </summary>
		public const string Connec_Ard_SensorFilterString = "Connec_Ard_Sensor.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify IconConnec_Ard_Act connector tool.
		/// </summary>
		public const string IconConnec_Ard_ActFilterString = "IconConnec_Ard_Act.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify IconConnecArdContro connector tool.
		/// </summary>
		public const string IconConnecArdControFilterString = "IconConnecArdContro.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify IconConnecIfIo connector tool.
		/// </summary>
		public const string IconConnecIfIoFilterString = "IconConnecIfIo.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify IconConnecIfDelay connector tool.
		/// </summary>
		public const string IconConnecIfDelayFilterString = "IconConnecIfDelay.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify IconConnecIoActua connector tool.
		/// </summary>
		public const string IconConnecIoActuaFilterString = "IconConnecIoActua.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify IconConnecIoSens connector tool.
		/// </summary>
		public const string IconConnecIoSensFilterString = "IconConnecIoSens.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify IconConnecIoDelay connector tool.
		/// </summary>
		public const string IconConnecIoDelayFilterString = "IconConnecIoDelay.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new JPBSDSJDFProyectoIPSToolboxHelperBase.
		/// </summary>
		protected JPBSDSJDFProyectoIPSToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSDomainModel.SingletonResourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 21;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconSensorsToolboxItem":
					// Add IconSensors shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconSensorsToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconSensorsToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconSensorsToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconSensors", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconSensorsToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.Sensors.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconControllerToolboxItem":
					// Add IconController shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconControllerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconControllerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconControllerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconController", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconControllerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.Contoller.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.Connec_Ard_SensorToolboxItem":

					// Add Connec_Ard_Sensor connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.Connec_Ard_SensorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("Connec_Ard_SensorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("Connec_Ard_SensorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Connec_Ard_Sensor", // F1 help keyword for the toolbox item.
						resourceManager.GetString("Connec_Ard_SensorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(Connec_Ard_SensorFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconArduinoToolboxItem":
					// Add IconArduino shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconArduinoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconArduinoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconArduinoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconArduino", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconArduinoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.Arduino.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconLedToolboxItem":
					// Add IconLed shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconLedToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconLedToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconLedToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconLed", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconLedToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.LedActuator.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconConnec_Ard_ActToolboxItem":

					// Add IconConnec_Ard_Act connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconConnec_Ard_ActToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconConnec_Ard_ActToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconConnec_Ard_ActToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconConnec_Ard_Act", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconConnec_Ard_ActToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(IconConnec_Ard_ActFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconLcdToolboxItem":
					// Add IconLcd shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconLcdToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconLcdToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconLcdToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconLcd", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconLcdToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.LCDActuator.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconBuzzerToolboxItem":
					// Add IconBuzzer shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconBuzzerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconBuzzerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconBuzzerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconBuzzer", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconBuzzerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.BuzzerActuator.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconDCmotorToolboxItem":
					// Add IconDCmotor shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconDCmotorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconDCmotorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconDCmotorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconDCmotor", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconDCmotorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.DCMotorActuator.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconIO1ToolboxItem":
					// Add IconIO1 shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconIO1ToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconIO1ToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconIO1ToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconIO1", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconIO1ToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.IO.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconDelay1ToolboxItem":
					// Add IconDelay1 shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconDelay1ToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						11, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconDelay1ToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconDelay1ToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconDelay1", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconDelay1ToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.Delay.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecArdControToolboxItem":

					// Add IconConnecArdContro connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecArdControToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						12, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconConnecArdControToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconConnecArdControToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconConnecArdContro", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconConnecArdControToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(IconConnecArdControFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfIoToolboxItem":

					// Add IconConnecIfIo connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfIoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						13, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconConnecIfIoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconConnecIfIoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconConnecIfIo", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconConnecIfIoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(IconConnecIfIoFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfDelayToolboxItem":

					// Add IconConnecIfDelay connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIfDelayToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						14, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconConnecIfDelayToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconConnecIfDelayToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconConnecIfDelay", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconConnecIfDelayToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(IconConnecIfDelayFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoActuaToolboxItem":

					// Add IconConnecIoActua connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoActuaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						15, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconConnecIoActuaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconConnecIoActuaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconConnecIoActua", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconConnecIoActuaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(IconConnecIoActuaFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoSensToolboxItem":

					// Add IconConnecIoSens connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoSensToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						16, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconConnecIoSensToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconConnecIoSensToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconConnecIoSens", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconConnecIoSensToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(IconConnecIoSensFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoDelayToolboxItem":

					// Add IconConnecIoDelay connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconConnecIoDelayToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						17, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconConnecIoDelayToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconConnecIoDelayToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconConnecIoDelay", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconConnecIoDelayToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(IconConnecIoDelayFilterString)
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconIf2ToolboxItem":
					// Add IconIf2 shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconIf2ToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						18, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconIf2ToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconIf2ToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconIf2", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconIf2ToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.If.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconInfrared2ToolboxItem":
					// Add IconInfrared2 shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconInfrared2ToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						19, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconInfrared2ToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconInfrared2ToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconInfrared2", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconInfrared2ToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.Infrared.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.InconTemperature2ToolboxItem":
					// Add InconTemperature2 shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.InconTemperature2ToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						20, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InconTemperature2ToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InconTemperature2ToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"InconTemperature2", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InconTemperature2ToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.Temperatue.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JPBSDSJDFProyectoIPS.IconLightSensor2ToolboxItem":
					// Add IconLightSensor2 shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JPBSDSJDFProyectoIPS.IconLightSensor2ToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						21, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("IconLightSensor2ToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("IconLightSensor2ToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("JPBSDSJDFProyectoIPSToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"IconLightSensor2", // F1 help keyword for the toolbox item.
						resourceManager.GetString("IconLightSensor2ToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JPBSDSJDFProyectoIPS.LightSensor.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.JPBSDSJDFProyectoIPS.JPBSDSJDFProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
