//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.JPBSDSJDFProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ISJProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"JPBSDSJDFProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID JPBSDSJDFProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JPBSDSJDFProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID JPBSDSJDFProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JPBSDSJDFProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewJPBSDSJDFProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JPBSDSJDFProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string JPBSDSJDFProyectoIPSPackageId = "62b8ed43-6ca4-4989-a421-adea1a15954c";
		
		// Editor factory identifier
		public const string JPBSDSJDFProyectoIPSEditorFactoryId = "c9ddf43b-7ad0-4743-80c8-5e2b5b072609";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string JPBSDSJDFProyectoIPSModelExplorerToolWindowId = "9042b9cc-2209-4a29-9c50-d24c373ddcc9";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.JPBSDSJDFProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string JPBSDSJDFProyectoIPSCommandSetId = "c6c3926d-a83a-4b39-b809-0e33e8dd31bb";
	}
}